### ISSUE TITLE
importing package

### ISSUE THREAD

**Issue by taunoe** [PacktPublishing/Programming-Microcontrollers-and-WebAssembly-with-TinyGo#3]
I have a problem with packages. Like when using keypad example:

`taunoerik@pop-os:~/controlling-keypad$ tinygo flash -target=arduino -port=/dev/ttyACM0 main.go
main.go:6:2: no required module provides package github.com/PacktPublishing/Creative-DIY-Microcontroller-Projects-with-TinyGo-and-WebAssembly/Chapter03/keypad; to add it:
	go get github.com/PacktPublishing/Creative-DIY-Microcontroller-Projects-with-TinyGo-and-WebAssembly/Chapter03/keypad

taunoerik@pop-os:~/controlling-keypad$ go get github.com/PacktPublishing/Creative-DIY-Microcontroller-Projects-with-TinyGo-and-WebAssembly/Chapter03/keypad
github.com/PacktPublishing/Creative-DIY-Microcontroller-Projects-with-TinyGo-and-WebAssembly/Chapter03/keypad imports
	machine: package machine is not in GOROOT (/usr/lib/go-1.16/src/machine)
`

**Comment by Nerzal** [comment]
I'll try to reproduce the problem.

In the meantime a workarround that should work could be to simply clone the complete repository into the correct path inside your GOPATH
And omit the use of go module in that case.

**Comment by Nerzal** [comment]
No problems in GOPATH mode. 
Going to check gomodule mode next.
![grafik](https://user-images.githubusercontent.com/9110370/129083076-e1097e34-de39-4788-9777-f102a2756608.png)

**Comment by Nerzal** [comment]
Also no problems in go module mode. 

![grafik](https://user-images.githubusercontent.com/9110370/129083388-86caa85b-572f-4bb8-a5c7-51d630058b07.png)

@taunoe as i have trouble to reproduce the issue, can you please provide a little more information? 
Like which tinygo version are you using? 

You can find out by executing the following command: `tinygo version`


Also if you are using go modules, the require section of the go.mod file should look similar to this: 

```
require (
	github.com/PacktPublishing/Creative-DIY-Microcontroller-Projects-with-TinyGo-and-WebAssembly v1.0.0
	tinygo.org/x/drivers v0.17.1
)
```

**Comment by Nerzal** [comment]
What you could try is go getting the complete project instead of the package. 

Using: `go get github.com/PacktPublishing/Creative-DIY-Microcontroller-Projects-with-TinyGo-and-WebAssembly/`

**Comment by taunoe** [comment]
Thank You!
The error was in the go.mod file. When the project is ready. Must run `go mod tidy` to get correct values.
And now I have no problem.

**Comment by Nerzal** [comment]
Perfect! I'm happy the project is running now :)
